services:
  - type: web
    name: my-backend-service
    env: python
    plan: free  # or 'starter', 'standard', etc.
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key
